# Generated by Django 3.2 on 2022-01-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContestantForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_no', models.CharField(max_length=20)),
                ('reg_email', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('reg_image', models.FileField(blank=True, null=True, upload_to='uploads/registration_images/')),
                ('amount', models.PositiveIntegerField(default=500)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('reg_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contestants.contesttype')),
            ],
        ),
    ]
