# Generated by Django 3.2 on 2022-01-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestantform',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDIND'), ('approved', 'APPROVED')], default='PENDING', max_length=15),
        ),
    ]
