# Generated by Django 3.2 on 2022-01-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0002_contestantform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestantform',
            name='reg_image',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/registration_images/'),
        ),
    ]
