# Generated by Django 3.2 on 2022-01-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0004_auto_20220128_0005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contestantform',
            options={'ordering': ['-date_reg'], 'verbose_name_plural': 'All Contestant'},
        ),
        migrations.AlterModelOptions(
            name='contesttype',
            options={'verbose_name_plural': 'contest type'},
        ),
        migrations.AlterField(
            model_name='contestantform',
            name='reg_image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='media/uploads/registration_images/'),
        ),
    ]
