# Generated by Django 3.2 on 2022-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_full_name_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_images', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'gallery',
                'verbose_name_plural': 'gallery images',
                'ordering': ['-g_images'],
            },
        ),
    ]
