# Generated by Django 3.2 on 2022-01-27 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='g_images',
            field=models.ImageField(null=True, upload_to='media/uploads/gallery/'),
        ),
    ]
