# Generated by Django 3.2 on 2022-01-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_gallery_g_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
